/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as publicLayoutRouteImport } from "./routes/(public)/layout";
import { Route as publicIndexRouteImport } from "./routes/(public)/index";
import { Route as publicSplatRouteImport } from "./routes/(public)/$$";

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: "/(public)",
  getParentRoute: () => rootRouteImport,
} as any);
const publicIndexRoute = publicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicSplatRoute = publicSplatRouteImport.update({
  id: "/$$",
  path: "/$$",
  getParentRoute: () => publicLayoutRoute,
} as any);

export interface FileRoutesByFullPath {
  "/$$": typeof publicSplatRoute;
  "/": typeof publicIndexRoute;
}
export interface FileRoutesByTo {
  "/$$": typeof publicSplatRoute;
  "/": typeof publicIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(public)": typeof publicLayoutRouteWithChildren;
  "/(public)/$$": typeof publicSplatRoute;
  "/(public)/": typeof publicIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/$$" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/$$" | "/";
  id: "__root__" | "/(public)" | "/(public)/$$" | "/(public)/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(public)": {
      id: "/(public)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof publicLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/": {
      id: "/(public)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof publicIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/$$": {
      id: "/(public)/$$";
      path: "/$$";
      fullPath: "/$$";
      preLoaderRoute: typeof publicSplatRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
  }
}

interface publicLayoutRouteChildren {
  publicSplatRoute: typeof publicSplatRoute;
  publicIndexRoute: typeof publicIndexRoute;
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicSplatRoute: publicSplatRoute,
  publicIndexRoute: publicIndexRoute,
};

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
