/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as publicLayoutRouteImport } from "./routes/(public)/layout";
import { Route as publicIndexRouteImport } from "./routes/(public)/index";
import { Route as publicSplatRouteImport } from "./routes/(public)/$$";
import { Route as publicResultIndexRouteImport } from "./routes/(public)/result/index";
import { Route as publicDocxtohtmlIndexRouteImport } from "./routes/(public)/docxtohtml/index";
import { Route as publicResultSubmissionIdRouteImport } from "./routes/(public)/result/$submissionId";
import { Route as publicExamExamIdRouteImport } from "./routes/(public)/exam/$examId";

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: "/(public)",
  getParentRoute: () => rootRouteImport,
} as any);
const publicIndexRoute = publicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicSplatRoute = publicSplatRouteImport.update({
  id: "/$$",
  path: "/$$",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicResultIndexRoute = publicResultIndexRouteImport.update({
  id: "/result/",
  path: "/result/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicDocxtohtmlIndexRoute = publicDocxtohtmlIndexRouteImport.update({
  id: "/docxtohtml/",
  path: "/docxtohtml/",
  getParentRoute: () => publicLayoutRoute,
} as any);
const publicResultSubmissionIdRoute =
  publicResultSubmissionIdRouteImport.update({
    id: "/result/$submissionId",
    path: "/result/$submissionId",
    getParentRoute: () => publicLayoutRoute,
  } as any);
const publicExamExamIdRoute = publicExamExamIdRouteImport.update({
  id: "/exam/$examId",
  path: "/exam/$examId",
  getParentRoute: () => publicLayoutRoute,
} as any);

export interface FileRoutesByFullPath {
  "/$$": typeof publicSplatRoute;
  "/": typeof publicIndexRoute;
  "/exam/$examId": typeof publicExamExamIdRoute;
  "/result/$submissionId": typeof publicResultSubmissionIdRoute;
  "/docxtohtml/": typeof publicDocxtohtmlIndexRoute;
  "/result/": typeof publicResultIndexRoute;
}
export interface FileRoutesByTo {
  "/$$": typeof publicSplatRoute;
  "/": typeof publicIndexRoute;
  "/exam/$examId": typeof publicExamExamIdRoute;
  "/result/$submissionId": typeof publicResultSubmissionIdRoute;
  "/docxtohtml": typeof publicDocxtohtmlIndexRoute;
  "/result": typeof publicResultIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(public)": typeof publicLayoutRouteWithChildren;
  "/(public)/$$": typeof publicSplatRoute;
  "/(public)/": typeof publicIndexRoute;
  "/(public)/exam/$examId": typeof publicExamExamIdRoute;
  "/(public)/result/$submissionId": typeof publicResultSubmissionIdRoute;
  "/(public)/docxtohtml/": typeof publicDocxtohtmlIndexRoute;
  "/(public)/result/": typeof publicResultIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/$$"
    | "/"
    | "/exam/$examId"
    | "/result/$submissionId"
    | "/docxtohtml/"
    | "/result/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/$$"
    | "/"
    | "/exam/$examId"
    | "/result/$submissionId"
    | "/docxtohtml"
    | "/result";
  id:
    | "__root__"
    | "/(public)"
    | "/(public)/$$"
    | "/(public)/"
    | "/(public)/exam/$examId"
    | "/(public)/result/$submissionId"
    | "/(public)/docxtohtml/"
    | "/(public)/result/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(public)": {
      id: "/(public)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof publicLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(public)/": {
      id: "/(public)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof publicIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/$$": {
      id: "/(public)/$$";
      path: "/$$";
      fullPath: "/$$";
      preLoaderRoute: typeof publicSplatRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/result/": {
      id: "/(public)/result/";
      path: "/result";
      fullPath: "/result/";
      preLoaderRoute: typeof publicResultIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/docxtohtml/": {
      id: "/(public)/docxtohtml/";
      path: "/docxtohtml";
      fullPath: "/docxtohtml/";
      preLoaderRoute: typeof publicDocxtohtmlIndexRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/result/$submissionId": {
      id: "/(public)/result/$submissionId";
      path: "/result/$submissionId";
      fullPath: "/result/$submissionId";
      preLoaderRoute: typeof publicResultSubmissionIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
    "/(public)/exam/$examId": {
      id: "/(public)/exam/$examId";
      path: "/exam/$examId";
      fullPath: "/exam/$examId";
      preLoaderRoute: typeof publicExamExamIdRouteImport;
      parentRoute: typeof publicLayoutRoute;
    };
  }
}

interface publicLayoutRouteChildren {
  publicSplatRoute: typeof publicSplatRoute;
  publicIndexRoute: typeof publicIndexRoute;
  publicExamExamIdRoute: typeof publicExamExamIdRoute;
  publicResultSubmissionIdRoute: typeof publicResultSubmissionIdRoute;
  publicDocxtohtmlIndexRoute: typeof publicDocxtohtmlIndexRoute;
  publicResultIndexRoute: typeof publicResultIndexRoute;
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicSplatRoute: publicSplatRoute,
  publicIndexRoute: publicIndexRoute,
  publicExamExamIdRoute: publicExamExamIdRoute,
  publicResultSubmissionIdRoute: publicResultSubmissionIdRoute,
  publicDocxtohtmlIndexRoute: publicDocxtohtmlIndexRoute,
  publicResultIndexRoute: publicResultIndexRoute,
};

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
